on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Check json schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Chain List schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schema.chain.json
          json_path_pattern: ./chainConfig/*.json$
      - name: Check Tokens List schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schema.token.json
          json_path_pattern: ./tokens/*.json$
